server:
  port: 8801

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  hibernate:
    hbm2ddl:
      auto: update
    show_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: "ritikagrawal1697@gmail.com"
    password: "#Ritik125"
    smtp:
      auth: true
      starttls:
        enable: true

interakt:
  apiKey: key
  apiSecret: password

sqlite:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:../kasera.db
  username: root
  password: password

