server:
  port: 8801

spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: MYSQL
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ritikagrawal1697@gmail.com"
    password: "#Ritik125"
    smtp:
      auth: true
      starttls:
        enable: true

interakt:
  apiKey: key
  apiSecret: password


